#!/usr/bin/env python
from __future__ import print_function
from __future__ import absolute_import

import os
import sys
import time
import re
from os import path
from io import open
from textwrap import dedent
import pkgutil
import subprocess
import xml.etree.ElementTree as xe
from shutil import copyfile
from math import sin, cos, radians


import ezdxf
#from ezdxf import bbox


__version__ = '0.1'

PIN_TS_BASE = 0x23420000
TEDIT_BASE = 0x23430000
PATH_BASE = 0x23440000
DEFAULT_FP="Pogopin:AutogeneratedPogopinFootprint"
DEFAULT_HOLE_DIA=1.7

def print_dxf_entity(e):
    print("LINE on layer: %s" % e.dxf.layer)
    print("start point: %s %s" % e.dxf.start)
    print("end point: %s %s" % e.dxf.end)

def print_dxf_arc_entity(e):
    print("ARC on layer: %s" % e.dxf.layer)
    print("start point: %s %s" % e.dxf.center)
    print("end point: %s %s" % (e.dxf.radius,e.dxf.start_angle))

def get_arc_edges(e):
    x0=e.dxf.center[0]+e.dxf.radius*cos(radians(e.dxf.start_angle))
    y0=e.dxf.center[1]+e.dxf.radius*sin(radians(e.dxf.start_angle))
    x1=e.dxf.center[0]+e.dxf.radius*cos(radians(e.dxf.end_angle))
    y1=e.dxf.center[1]+e.dxf.radius*sin(radians(e.dxf.end_angle))
    #print("ARC on layer: %s" % e.dxf.layer)
    #print("center: %s %s" % e.dxf.center)
    #print("radius: %s" % (e.dxf.radius))
    #print("angles: %s %s" % (e.dxf.start_angle, e.dxf.end_angle))
    #print("start point: %s %s" % (x0,y0))
    #print("end point: %s %s" % (x1,y1))
    return [(x0,y0),(x1,y1)]

def is_number(s):
    try:
        float(s)
        return True
    except TypeError:
        return False
    except ValueError:
        return False

def sch_template(name, pins, xspace=1500, yspace=200, sht_cnt=1, sht_idx=1, parent_sheet=False):
    templ = '''
        EESchema Schematic File Version 5
        EELAYER 30 0
        EELAYER END
        $Descr A4 11693 8268
        encoding utf-8
        Sheet {sht_idx} {sht_cnt}
        Title "{name}"
        Date "{date}"
        Rev ""
        Comp ""
        Comment1 ""
        Comment2 ""
        Comment3 ""
        Comment4 ""
        Comment5 ""
        Comment6 ""
        Comment7 ""
        Comment8 ""
        Comment9 ""
        $EndDescr
        {components}
        $EndSCHEMATC
    '''
    
    # Template for sheet in case creating parent sheet
    sheet_templ='''
    $Sheet
    S 8300 3725 625  200 
    F0 "{name}" 50
    F1 "{name.sch}" 50
    $EndSheet
    '''

    components_list = []
    for i, pin in enumerate(pins):
        #print(pin) # Show contents of dictionary
        uid = pin.get('uid')
        identifier = pin.get('identifier')
        #x = pin.get('x # Board position')
        #y = pin.get('y # Board position')
        netname = pin.get('netname')
        tmp = pin.get('diamOrModel')

        footprint=DEFAULT_FP
        if not is_number(tmp):
           footprint = pin.get('diamOrModel')

        value = 'pogopin'
        x, y = 1000 + (i//32)*xspace , 1000 + (i%32)*yspace
        components_list.append(dedent('''
            $Comp
            L Connector:Conn_01x01_Female {identifier}
            U 1 1 {uid}
            P {x} {y}
            F 0 "{identifier}" H {xmoff} {ypoff} 50  0000 R CNN
            F 1 "{value}" H {xpoff} {y} 50  0000 L CNN
            F 2 "{footprint}" H {x} {y} 50  0001 C CNN
            F 3 "~" H {x} {y} 50  0001 C CNN
                    1    {x} {y}
                    -1   0    0    1   
            $EndComp
            Wire Wire Line
                    {wx0} {wy0} {wx1} {wy1}
            Text GLabel {wx1} {wy0} 2    50  BiDi ~ 0
            {netname}
            '''.format(
                   i=i,
                   uid=uid,
                   identifier=identifier,
                   value=value,
                   x=x,y=y,
                   xmoff=x-50,xpoff=x+50,
                   ymoff=y-50,ypoff=y+50,
                   #wx0=x+200,wy0=y,wx1=x+1000,wy1=y,
                   wx0=x+200,wy0=y,wx1=x+300,wy1=y,
                   netname=netname,
                   footprint=footprint,
               )).strip())

            #Older wire implementation: - replaced with GLabel
            #Wire Wire Line
            #        {wx0} {wy0} {wx1} {wy1}
            #Text Label {wx1} {wy0} 2    50   ~ 0

    components='\n'.join(components_list)
    return dedent(templ).lstrip().format(
         sht_idx=sht_idx, sht_cnt=sht_cnt,
         components=components,name=name,date=time.strftime("%d %b %Y")
       )
def pcb_template(outline, pins, annular=0.25, xoff=0, yoff=0, hole_dia=None):
    if hole_dia is None:
        hole_dia=DEFAULT_HOLE_DIA
    pcb_templ = '''
        (kicad_pcb (version 20190605) (host pogojig "(5.1.9)-1")

          (general
            (thickness 1.6)
            (drawings {plen})
            (tracks 0)
            (zones 0)
            (modules {plen})
            (nets {plenp1})
          )

          (page "A4")
          (layers
            (0 "F.Cu" signal)
            (31 "B.Cu" signal)
            (32 "B.Adhes" user)
            (33 "F.Adhes" user)
            (34 "B.Paste" user)
            (35 "F.Paste" user)
            (36 "B.SilkS" user)
            (37 "F.SilkS" user)
            (38 "B.Mask" user)
            (39 "F.Mask" user)
            (40 "Dwgs.User" user)
            (41 "Cmts.User" user)
            (42 "Eco1.User" user)
            (43 "Eco2.User" user)
            (44 "Edge.Cuts" user)
            (45 "Margin" user)
            (46 "B.CrtYd" user)
            (47 "F.CrtYd" user)
            (48 "B.Fab" user)
            (49 "F.Fab" user)
          )

          (setup
            (last_trace_width 0.25)
            (trace_clearance 0.2)
            (zone_clearance 0.508)
            (zone_45_only no)
            (trace_min 0.2)
            (via_size 0.8)
            (via_drill 0.4)
            (via_min_size 0.4)
            (via_min_drill 0.3)
            (uvia_size 0.3)
            (uvia_drill 0.1)
            (uvias_allowed no)
            (uvia_min_size 0.2)
            (uvia_min_drill 0.1)
            (edge_width 0.1)
            (segment_width 0.2)
            (pcb_text_width 0.3)
            (pcb_text_size 1.5 1.5)
            (mod_edge_width 0.15)
            (mod_text_size 1 1)
            (mod_text_width 0.15)
            (pad_size 1.524 1.524)
            (pad_drill 0.762)
            (pad_to_mask_clearance 0)
            (aux_axis_origin 0 0)
            (visible_elements 7FFFFFFF)
            (pcbplotparams
              (layerselection 0x010fc_ffffffff)
              (usegerberextensions false)
              (usegerberattributes false)
              (usegerberadvancedattributes false)
              (creategerberjobfile false)
              (excludeedgelayer true)
              (linewidth 0.100000)
              (plotframeref false)
              (viasonmask false)
              (mode 1)
              (useauxorigin false)
              (hpglpennumber 1)
              (hpglpenspeed 20)
              (hpglpendiameter 15.000000)
              (psnegative false)
              (psa4output false)
              (plotreference true)
              (plotvalue true)
              (plotinvisibletext false)
              (padsonsilk false)
              (subtractmaskfromsilk false)
              (outputformat 1)
              (mirror false)
              (drillshape 1)
              (scaleselection 1)
              (outputdirectory ""))
          )

          (net 0 "")
          {{net_defs}}

          (net_class "Default" "This is the default net class."
            (clearance 0.2)
            (trace_width 0.25)
            (via_dia 0.8)
            (via_drill 0.4)
            (uvia_dia 0.3)
            (uvia_drill 0.1)
            {{net_class_defs}}
          )
          
          {{module_defs}}

          {{edge_cuts}}
        )'''.format(version=__version__,plen=len(pins),plenp1=len(pins)+1)

    module_defs = []
    net_defs = []
    net_class_defs = []
    for i, pin in enumerate(pins):
        uid = pin.get('uid')
        identifier = pin.get('identifier')
        x = float(pin.get('x'))+xoff # Board position
        y = float(pin.get('y'))+yoff # Board position
        netname = pin.get('netname')
        tmp = pin.get('diamOrModel')

        footprint=DEFAULT_FP
        if not is_number(tmp):
           footprint = pin.get('diamOrModel')

        pad_dia = hole_dia + 2*annular

        mod = '''
          (module "{footprint}" (layer "F.Cu") (tedit {teditb:08X}) (tstamp {pintsb:08X})
            (at {x} {y})
            (descr "Pogo pin {i}")
            (tags "test point plated hole")
            (path "/{uid}")
            (attr virtual)
            (fp_text reference "{identifier}" (at 0 -{label_off}) (layer "F.SilkS")
              (effects (font (size 1 1) (thickness 0.15)))
            )
            (fp_text user "{identifier}" (at 0 -{label_off}) (layer "B.SilkS")
              (effects (font (size 1 1) (thickness 0.15)) (justify mirror))
            )
            (fp_text user "{netname}" (at 0 {label_off}) (layer "F.SilkS")
              (effects (font (size 1 1) (thickness 0.15)))
            )
            (fp_text value "pogo pin {i}" (at 0 {label_off}) (layer "F.Fab")
              (effects (font (size 1 1) (thickness 0.15)))
            )
            (fp_text user "%R" (at 0 -{label_off}) (layer "F.Fab")
              (effects (font (size 1 1) (thickness 0.15)))
            )
            (fp_circle (center 0 0) (end {crt_r} 0) (layer "F.CrtYd") (width 0.05))
            (fp_circle (center 0 0) (end {crt_r} 0) (layer "B.CrtYd") (width 0.05))
            (fp_circle (center 0 0) (end 0 -{silk_r}) (layer "F.SilkS") (width 0.12))
            (fp_circle (center 0 0) (end 0 -{silk_r}) (layer "B.SilkS") (width 0.12))
            (pad "1" thru_hole circle (at 0 0) (size {pad_dia} {pad_dia}) (drill {hole_dia}) (layers *.Cu *.Mask)
              (net {ip1} "{netname}"))
          )'''.format(
              i=i,ip1=i+1,
              identifier=identifier,
              netname=netname,
              pad_dia=pad_dia,hole_dia=hole_dia,
              x=x,y=y,
              teditb=TEDIT_BASE+i,
              uid=uid,
              pintsb=PIN_TS_BASE+i,
              label_off=pad_dia/2+1,
              crt_r=pad_dia/2+0.25,
              silk_r=pad_dia/2+0.15,
              footprint=footprint,
              )
        module_defs.append(mod)
        net_defs.append('(net {ip1} "{netname}")'.format(ip1=i+1,netname=netname))
        net_class_defs.append('(add_net "{netname}")'.format(netname=netname))

    edge_cuts = [ '(gr_line (start {x1} {y1}) (end {x2} {y2}) (layer "Edge.Cuts") (width 0.05))'.format(x1=x1+xoff,y1=y1+yoff,x2=x2+xoff,y2=y2+yoff)
                  for (x1, y1), (x2, y2) in outline ]

    return dedent(pcb_templ).format(
            net_defs='\n'.join(net_defs),
            net_class_defs='\n'.join(net_class_defs),
            module_defs='\n'.join(module_defs),
            edge_cuts='\n'.join(edge_cuts))



if __name__ == '__main__':
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument('outline', metavar='outline.dxf', help='Board outline DXF')
    parser.add_argument('output', default='kicad', help='Output directory/project name and path')
    parser.add_argument('--testpins', '-t', metavar='TESTPINS', default="DEMO1:20:20:NETNAME1,DEMO2:60:80:NETNAME2",help='List of test pins NAME1:X1:Y1:NETNAME1:diam1OrModel?,NAME2:X2:Y2:NETNAME2:diam1OrModel?')
    parser.add_argument('--xspace', '-x', type=int, default=1500, help='Schematic pin X spacing in mil (default: 1000)')
    parser.add_argument('--yspace', '-y', type=int, default=200, help='Schematic pin Y spacing in mil (default: 200)')
    parser.add_argument('--annular', '-a', type=float, default=0.25, help='Pogo pin annular ring width in mm (default: 0.25)')
    parser.add_argument('--diameter', '-d', type=float, default=DEFAULT_HOLE_DIA, help='Pogo pin diameter in mm (default: %f)' % (DEFAULT_HOLE_DIA))
    parser.add_argument('--name', '-n', default='jig', help='Output KiCAD project name')
    args = parser.parse_args()

    pattern = re.compile(
      r'(?P<iden>[^:,]+)'
      +':(?P<x>[^:,]+)'
      +':(?P<y>[^:,]+)'
      +':(?P<netname>[^:,]+)'
      +'(:(?P<diamOrModel>[^,]+))?'
      )
    pins=[]
    i=0
    for m in re.finditer(pattern,args.testpins):
        i+=1
        identifier=m.group('iden')
        x=m.group('x')
        y=m.group('y')
        netname=m.group('netname')
        diamOrModel=m.group('diamOrModel')
        uid="{val:08X}".format(val=PATH_BASE+i)
        #print('Iden:%s' % (identifier)) # Show identifier, for debugging
        pins.append({'identifier':identifier,
                 'x':x,'y':y,
                 'netname':netname,'diamOrModel':diamOrModel,
                 'uid':uid,
             })

    if not path.exists(args.output):
        os.mkdir(args.output)

    if not path.isdir(args.output):
        raise SystemError(strf(F('Output path "{args.output}" is not a directory')))

    #pins = [ (
    #            (page_x + px_to_mm(x) + px_to_mm(w)/2,
    #             page_y - page_h + px_to_mm(y) + px_to_mm(w)/2),
    #            px_to_mm(w)) for x, y, w, h in dims ]
    #pins = [ ( (10, 20), 1 ), ( (100,30), 2) ]

    doc = ezdxf.readfile(args.outline)
    outline = []
    msp=doc.modelspace().query('LINE')
    MINX=20
    MAXX=280
    MINY=13
    MAXY=166
    xmin=float('inf') 
    ymin=float('inf') 
    xmax=0
    ymax=0
    for line in msp:
        #print_dxf_entity(line)
        try:
          (x1, y1), (x2, y2) = line.dxf.start, line.dxf.end
          xmin=min(xmin,x1,x2)
          xmax=max(xmax,x1,x2)
          ymin=min(ymin,-y1,-y2)
          ymax=max(ymax,-y1,-y2)
          outline.append(((x1, -y1), (x2, -y2)))
        except:
          abc=None
    msp=doc.modelspace().query('ARC')
    for arc in msp:
        (x1, y1), (x2, y2) = get_arc_edges(arc)
        try:
          (x1, y1), (x2, y2) = get_arc_edges(arc)
          xmin=min(xmin,x1,x2)
          xmax=max(xmax,x1,x2)
          ymin=min(ymin,-y1,-y2)
          ymax=max(ymax,-y1,-y2)
          outline.append(((x1, -y1), (x2, -y2)))
        except:
          abc=None

    width=(xmax-xmin)
    height=(ymax-ymin)
    midx=(xmin+xmax)/2
    midy=(ymin+ymax)/2
    xoff=(MAXX+MINX)/2-midx
    yoff=(MAXY+MINY)/2-midy
    r=5
    xoff=(xoff//r)*r
    yoff=(yoff//r)*r
   
    name=args.name
    sch_name=path.join(args.output, '{name}.sch').format(name=name)
    pcb_name=path.join(args.output, '{name}.kicad_pcb').format(name=name)
    pro_name=path.join(args.output, '{name}.pro').format(name=name)
    lib_name=path.join(args.output, '{name}-cache.lib').format(name=name)
    template_path=os.path.dirname(os.path.realpath(__file__))+'/templates/'

    with open(sch_name, 'w', encoding='utf8') as sch:
        title='{name} generated schematic (PogoJig v{version})'.format(name=name,version=__version__)
        sch.write(sch_template(title, pins, xspace=args.xspace, yspace=args.yspace).decode('utf8'))

    with open(pcb_name, 'w', encoding='utf8') as pcb:
        pcb.write(pcb_template(outline, pins, hole_dia=args.diameter, annular=args.annular,xoff=xoff,yoff=yoff).decode('utf8'))

    with open(pro_name, 'w', encoding='utf8') as f:
        with open(template_path+'kicad.pro', 'r') as s:
            f.write(s.read())
            s.close()
            f.close()

    with open(lib_name, 'w', encoding='utf8') as f:
        with open(template_path+'kicad-cache.lib', 'r') as s:
            f.write(s.read())
            s.close()
            f.close()

